# Generated by Django 4.2.3 on 2023-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Greeting",
        ),
        migrations.AlterField(
            model_name="registry",
            name="default_messages",
            field=models.ManyToManyField(blank=True, to="registry.defaultmessage"),
        ),
    ]
